msm-qdsp6v2-codecs-objs := aac_in.o amrnb_in.o amrwb_in.o audio_aac.o \
            audio_alac.o audio_amrnb.o audio_amrwb.o \
            audio_amrwbplus.o audio_ape.o audio_evrc.o \
            audio_g711alaw.o audio_g711mlaw.o audio_hwacc_effects.o \
            audio_mp3.o audio_multi_aac.o audio_qcelp.o \
            audio_utils_aio.o audio_utils_aio.h audio_utils.o \
            audio_utils.h audio_wma.o audio_wmapro.o evrc_in.o \
            g711alaw_in.o g711mlaw_in.o q6audio_common.h \
            q6audio_v2_aio.o q6audio_v2.o qcelp_in.o
obj-$(CONFIG_MSM_QDSP6V2_CODECS) += msm-qdsp6v2-codecs.o
